version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microsoft-graph-webhook
    ports:
      - "8000:8000"
    environment:
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - LOG_LEVEL=INFO
      
      # Microsoft Graph Configuration (override with your values)
      # - TENANT_ID=your-tenant-id
      # - CLIENT_ID=your-client-id
      # - CLIENT_SECRET=your-client-secret
      # - ACCESS_TOKEN=your-access-token
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
